### ISSUE TITLE
Gem error

### ISSUE THREAD

**Issue by Victorgf87** [RecastAI/SDK-ruby#1]
Hello, I am having a problem. I installed your gem by adding it to gemfile (gem 'RecastAI') and I am getting the following error

>
/Users/nabe/.rvm/gems/ruby-2.2.1/gems/RecastAI-1.1.0/lib/RecastAI.rb:14:in `require': cannot load such file -- awesome_print (LoadError)
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/RecastAI-1.1.0/lib/RecastAI.rb:14:in `<top (required)>'
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/nabe/Desktop/Licens/config/application.rb:7:in `<top (required)>'
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/nabe/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
>

I am using ruby 2.2.1 and Rails 4.2.5
Thanks for your help

**Comment by PaulRenvoise** [comment]
Hi,
Just pushed a version (1.1.1) fixing this unfortunate behavior.
I forgot to remove the `require 'awesome_print'` used in development, my bad!

Cheers, and happy coding :)

**Comment by Victorgf87** [comment]
Thank you so much! I will try it in a moment!
