### ISSUE TITLE
No namespace on binaries

### ISSUE THREAD

**Issue by Uelb** [RecastAI/SDK-ruby#5]
The file binary overrides the default file utility tool provided as a BSD general command, is it possible to change the name of the binary so that it does not prevent one from using the file tool ?

**Comment by PaulRenvoise** [comment]
Hi Uelb,

Thanks for the feedback, I just release a patched version (3.1.3) which replace the text and file binaries by another called recastcli with more command line options.

Hopefully you'll be able to use file again :)

Cheers,
